config/routes.rb
SeriesTracker::Application.routes.draw do

  resources :users, :programs # Consider User as an REST resource with GET, POST, PUT, DELETE mapped as Rails actions
  resources :sessions, only: [:create, :destroy]

  root 'welcome#index'

  match '/signup' ,  to: 'users#new',        via: [:get, :post]
  match '/signin' ,  to: 'sessions#create',  via: 'post'
  match '/signout',  to: 'sessions#destroy', via: 'delete'

  match '/search',          to: 'programs#search', via: 'get'
  match '/program_details', to: 'programs#show',   via: 'get'

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :season
  has_many :users, through: :episode
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :program


   # The touple (:user_id, :program_id) must be unique, so the same Show does not
   # appear more than one time
  validates_uniqueness_of :user_id, scope: :program_id

end

app/models/program.rb
class Program < ActiveRecord::Base

  serialize :created_by
  serialize :episode_run_time
  serialize :genres
  serialize :origin_country
  serialize :seasons
  serialize :languages

  has_many :favorites
  has_many :users, through: :favorites

  def release_year
    first_air_date.nil? ? "unknow" : first_air_date.year
  end

  def creators
    str = ""
    created_by.each {|creator| str += creator['name'] + ", "}
    str
  end

  def countries
    str = ""
    origin_country.each {|country| str += country + ", "}
    str
  end

end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :program
  has_many :episodes
end

app/models/user.rb
class User < ActiveRecord::Base


    has_many :favorites
    has_many :programs, through: :favorites


    # Allowed by gem bcrypt-ruby to encypt passwords.
    has_secure_password

    # Do some information treatment before save it on database.
    before_save do |user|
        user.email = email.downcase # To avoid conflicts on database store all emails as lower case.
        user.remember_token = SecureRandom.urlsafe_base64 # Generates a unique id for each user, used for session management.
    end

    # REGEX to validate emails strings with the format [STRING]@[STRING].[STRING]
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    # Field validations
    validates :name, presence: true, length: { minimum:1, maximum:50 }
    validates :surname, presence: true, length: { minimum:1, maximum:50 }
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :birthday, presence: true
    validates :gender, presence: true, inclusion: {in: ['MALE', 'FEMALE']}
    validates :password, presence: true, length: { minimum:6 }
    validates :password_confirmation, presence:true

end

app/models/watched_episode.rb
class WatchedEpisode < ActiveRecord::Base
  belongs_to :user
  belongs_to :episode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include SessionsHelper

  protect_from_forgery with: :exception
  before_filter :set_config

  Tmdb::Api.key("2701947a8f4b238d3f1ef3b98f51922a") # TMDB key

  def set_config
    @tmdb_config = Tmdb::Configuration.new
  end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  def show
      @program = get_or_save_program(params[:tmdb_id])
  end

  def update
    program = Program.find(params[:id])

    new_favorite_list = Favorite.new(user_id:current_user.id, program_id:program.id)

    if new_favorite_list.save
      flash[:success] = "New Show added!"
    else
      flash[:warning] = "This Show is already in your favorites list!"
      redirect_to program
      return
    end
    redirect_to current_user
  end

  def destroy
    current_user.favorites.find_by_program_id(params[:id]).destroy
    flash[:success] = "The show was removed!"
    redirect_to current_user
  end

  def search
    tmdb_search_result_set = Tmdb::TV.find(params[:q])

    @programs_list = []
    tmdb_search_result_set.each { |tmdb_result| @programs_list.push(get_or_save_program(tmdb_result.id)) }

    render 'list'
  end

  private
    def get_or_save_program(tmdb_id)
      existing_program = Program.find_by_tmdb_id(tmdb_id)

      if existing_program.nil?

        data = Tmdb::TV.detail(tmdb_id)

        new_program = Program.new

        new_program.tmdb_id = data.id
        new_program.backdrop_path = data.backdrop_path
        new_program.original_name = data.original_name
        new_program.first_air_date = data.first_air_date
        new_program.poster_path = data.poster_path
        new_program.popularity = data.popularity
        new_program.name = data.name
        new_program.vote_average = data.vote_average
        new_program.vote_count = data.vote_count
        new_program.created_by = data.created_by
        new_program.episode_run_time = data.episode_run_time
        new_program.genres = data.genres
        new_program.homepage = data.homepage
        new_program.in_production = data.in_production
        new_program.languages = data.languages
        new_program.last_air_date = data.last_air_date
        new_program.number_of_episodes = data.number_of_episodes
        new_program.number_of_seasons = data.number_of_seasons
        new_program.origin_country = data.origin_country
        new_program.overview = data.overview
        new_program.seasons = data.seasons
        new_program.status = data.status

        blank_image = "no_image.png"

        new_program.small_image    = data.poster_path.nil? ? blank_image : @tmdb_config.base_url + "w154" + data.poster_path
        new_program.medium_image   = data.poster_path.nil? ? blank_image : @tmdb_config.base_url + "w342" + data.poster_path
        new_program.large_image    = data.poster_path.nil? ? blank_image : @tmdb_config.base_url + "w500" + data.poster_path
        new_program.original_image = data.poster_path.nil? ? blank_image : @tmdb_config.base_url + "original" + data.poster_path

        new_program.save
        new_program
      else
        existing_program
      end

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash[:error] = 'Invalid email/password combination'
      redirect_to root_url
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # Create a new user on database, respond to [POST]/users/new
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new' # Default /user/new
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    if !signed_in? && !current_user.equal?(@user)
      redirect_to root_path
    end
  end

  # New mass-assignment protection for Rails 4
  private
    def user_params
      params.require(:user).permit(:name, :surname, :gender, :birthday, :email, :password, :password_confirmation)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
      # Create a user instance for the default registration form
      @user = User.new
      @query
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
  def is_current_user_favorite?(program)
    current_user.programs.include?(program)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
     cookies.permanent[:remember_token] = user.remember_token
  end

  def sign_out
     self.current_user = nil
     cookies.delete(:remember_token)
  end

  def current_user=(user)
     @current_user = user
  end

  def current_user
     if @current_user.nil?
         @current_user = User.find_by_remember_token(cookies[:remember_token])
     end
     @current_user
  end

  def signed_in?
     !current_user.nil? # A user is signed in if current_user is NOT nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    Developed by Guilherme Amaral
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-header">
            <%= link_to "SERIES TRACKER", root_path, id: "logo", class: "navbar-brand" %>
        </div>

        <% if !signed_in? %>
            <%= render 'layouts/login' %>
        <% else %>
            <%= form_tag("/search", method: "get", class: "navbar-form navbar-left") do %>
                <div class="form-group">
                <%= text_field_tag(:q, nil, placeholder: "Search...", class: "form-control") %>
                 </div>
                <%= submit_tag("Search", class: "btn btn-default") %>
            <% end %>

            <div class="collapse navbar-collapse bs-js-navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                            <li role="presentation"><%= link_to "Profile", current_user %></li>
                            <li role="presentation" class="divider"></li>
                            <li role="presentation"><%= link_to "Sign out", signout_path, method: "delete" %></li>
                        </ul>
                    </li>
                </ul>
            </div>
        <% end %>

</div>

app/views/layouts/_login.html.erb
<%= form_for( :session, url: '/signin', :html => { :class => "navbar-form navbar-right"} ) do |f| %>
<div class="form-group">
  <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
</div>
<div class="form-group">
  <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
</div>
<%= f.submit "Sign in", class: "btn btn-success" %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="public/favicon.png">

  <!-- Bootstrap core JavaScript -->
  <%= javascript_include_tag "application" %>

  <title>
    Series Tracker
  </title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <%= render 'layouts/header' %>

  <% if signed_in? %>
    <div id="wrapper">
      <!-- Page content -->
      <div id="page-content-wrapper">

        <!-- Keep all page content within the page-content inset div! -->
        <div class="page-content inset">
          <div class="container">
            <%= render 'layouts/messages' %>
          </div>
          <div class="row">
            <div class="col-md-12">
              <%= yield %>
            </div>
          </div>
          <hr>
          <div class="container">
            <%= render 'layouts/footer' %>
          </div> <!-- /container -->
        </div>
      </div>
    </div>
  <% else %>
    <div class="container">
      <%= render 'layouts/messages' %>
    </div>
    <%= yield %>
    <hr>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
  <% end %>

</body>
</html>

app/views/programs/list.html.erb
<div class="container">
  <div class="container-fluid well span6">
    <div class="row-fluid">
      <%= render 'shared/programs_list', programs: @programs_list, list_title: 'Search Result' %>
    </div>
  </div>
</div>

app/views/programs/show.html.erb
<% provide(:title, @program.name) %>

<div class="container">
  <div class="container-fluid well span6">
    <div class="row-fluid">

      <div>
        <div id="leftcolumn">
          <div>
            <%= image_tag(@program.small_image) %>
          </div><br>
          <div>
            <%= form_for @program do |f| %>
            <% if is_current_user_favorite?(@program) %>
            <%= link_to "REMOVE", program_path(id: @program.id), method: "delete", class: "btn btn-danger" %>
            <% else %>
            <%= f.submit "ADD", class: "btn btn-success" %>
            <% end %>
            <% end %>
          </div>
        </div>

        <div id="rightcolumn">
          <p>
            <strong>Title:</strong>
            <span><%= @program.name %> (<%= @program.release_year %>)</span>
          </p>
          <p>
            <strong>Score:</strong>
            <span><%= @program.vote_average %></span>
          </p>
          <p>
            <strong>Creators:</strong>
            <span><%= @program.creators %></span>
          </p>
          <p>
            <strong>Country:</strong>
            <span><%= @program.countries %></span>
          </p>
          <p>
            <strong>Description:</strong>
            <span><%= @program.overview %></span>
          </p>
        </div>

        <!-- Needed because other elements inside ProfilePage have floats -->
        <div style="clear:both"></div><br>

        <div class="panel-group" id="accordion">

        <% @program.seasons.each do |season| %>
        <% s_title = season["season_number"]==0 ? "Season Specials" : "Season "+season["season_number"].to_s %>
        <% _href = "collapse" + season["season_number"].to_s  %>

          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#<%= _href %>">
                  <%= s_title %>
                </a>
              </h4>
            </div>
            <div id="<%= _href %>" class="panel-collapse collapse">
              <div class="panel-body">
                TODO: EPISODES
              </div>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<div class="container">
  <% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/shared/_programs_list.html.erb
<table class="table table-striped table-bordered table-condensed">
  <h3><%= list_title %></h3>
  <thead>
    <tr>
      <th>Cover</th>
      <th>Title</th>
      <th>Year</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% programs.each do |p| %>
    <tr>
      <td><%= image_tag(p.small_image) %></td>
      <td><%= p.name %></td>
      <td><%= p.release_year %></td>
      <td><%= p.overview %></td>
      <td><%= link_to 'View',
        program_details_path(tmdb_id: p.tmdb_id), class: "btn btn-info" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="container">
  <div class="row">
  <div class="col-md-4"></div>
    <div class="col-md-4">
      <h2 class="form-signin-heading">Sign Up</h2>

      <%= form_for(@user, :html => { :class => "form-signin"}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <p>
        <table>
          <tr>
            <td>
              <%= f.label :name %>
              <%= f.text_field :name , class: "form-control" %>
            </td>
            <td></td>
            <td>
              <%= f.label :surname %>
              <%= f.text_field :surname, class: "form-control" %>
            </td>
          </tr>
        </table>
      </p>
      <p>
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </p>
      <p>
        <%= f.label :birthday %>
        <%= f.date_field :birthday, class: "form-control" %>
      </p>
      <p><span>
        <%= f.radio_button :gender, 'MALE' %> Male
        </span>
        <span>
        <%= f.radio_button :gender, 'FEMALE' %> Female
        </span>
      </p>
      <p>
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </p>
      <p>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </p>
      <p>
        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
      </p>
      <% end %>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="container">
  <div class="container-fluid well span6">
    <div class="row-fluid">
      <table>
        <tr>
          <td>
            <div class="span2" >
              <%= gravatar_for @user %>
            </div>
          </td>
          <td>
            <div class="span8">
              <h3> <%= @user.name %> <%= @user.surname %></h3>
              <h6> Member since: <%= @user.created_at.to_date %></h6>
            </div>
          </td>
        </tr>
      </table>
    </div>
    <div class="span12">
      <hr>

     <%= render 'shared/programs_list', programs: @user.programs, list_title: 'My Shows' %>

    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <p>The time is now: <%= Time.now %></p>
    <% if !signed_in? %>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>